export default {
  "jp": {
    "xabarlar": "メッセージ",
    "saqlanganlar": "保存されたメッセージ",
    "linklar": "リンク集",
    "sozlamalar": "設定",
    "ism": "名前",
    "familiya": "苗字",
    "id_raqami": "ID番号",
    "telefon_raqami": "電話番号",
    "raqamni_ozgartirish": "電話番号を変更する",
    "parolni_ozgartirish": "パスワードを変更する",
    "tilni_ozgartirish": "言語を変更する",
    "akkountdan_chiqish": "サインアウト",
    "web_sahifasi": "webページ",
    "youtube_sahifasi": "youtubeページ",
    "facebook_sahifasi": "facebookページ",
    "instagram_sahifasi": "instagramページ",
    "telegram_sahifasi": "telegramチャンネル",
    "twitter_sahifasi": "twitter(X)ページ",
    "login": "ログイン",
    "login_text": "アプリケーションを使用することにより、お客様は当社の規約とポリシーに同意したものとみなされます。",
    "login_button": "ログイン",
    "login_help": "パスワードをお忘れですか？",
    "login_mail": "メールアドレス",
    "login_password": "パスワード",
    "login_error": "電子メールまたはパスワードが間違っている",
  },
  "uzb": {
    "xabarlar": "Xabarlar",
    "saqlanganlar": "Saqlanganlar",
    "linklar": "Linklar",
    "sozlamalar": "Sozlamalar",
    "ism": "ism",
    "familiya": "familiya",
    "id_raqami": "id raqami",
    "telefon_raqami": "telefon raqami",
    "raqamni_ozgartirish": "Raqamni o'zgartirish",
    "parolni_ozgartirish": "Parolni o'zgartirish",
    "tilni_ozgartirish": "Tilni o'zgartirish",
    "akkountdan_chiqish": "Akkountdan chiqish",
    "web_sahifasi": "Web sahifasi",
    "youtube_sahifasi": "Youtube sahifasi",
    "facebook_sahifasi": "Facebook sahifasi",
    "instagram_sahifasi": "Instagram sahifasi",
    "telegram_sahifasi": "Telegram sahifasi",
    "twitter_sahifasi": "Twitter(X) sahifasi",
    "login": "Kirish",
    "login_text": "Ushbu dasturga kirish orqali siz bizning shart va siyosatimizga rozilik bildirasiz",
    "login_button": "Kirish",
    "login_help": "Parolni unutdingizmi?",
    "login_mail": "E-pochta manzili",
    "login_password": "Parol",
    "login_error": "E-pochta yoki parol noto'g'ri kiritilgan",
  },
  "eng": {
    "xabarlar": "Messages",
    "saqlanganlar": "Saved",
    "linklar": "Links",
    "sozlamalar": "Settings",
    "ism": "name",
    "familiya": "surname",
    "id_raqami": "id number",
    "telefon_raqami": "phone number",
    "raqamni_ozgartirish": "Change number",
    "parolni_ozgartirish": "Change password",
    "tilni_ozgartirish": "Change language",
    "akkountdan_chiqish": "Sign out",
    "web_sahifasi": "Web page",
    "youtube_sahifasi": "YouTube page",
    "facebook_sahifasi": "Facebook page",
    "instagram_sahifasi": "Instagram page",
    "telegram_sahifasi": "Telegram channel",
    "twitter_sahifasi": "Twitter(X) page",
    "login": "Login",
    "login_text": "By using our application you agree to our terms and policies",
    "login_button": "Login",
    "login_help": "Forgot password?",
    "login_mail": "Email Address",
    "login_password": "Password",
    "login_error": "email or password is incorrect",
  }
}