"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    "jp": {
        "xabarlar": "メッセージ",
        "saqlanganlar": "保存されたメッセージ",
        "linklar": "リンク集",
        "sozlamalar": "設定",
        "ism": "名前",
        "familiya": "苗字",
        "id_raqami": "ID番号",
        "telefon_raqami": "電話番号",
        "raqamni_ozgartirish": "電話番号を変更する",
        "parolni_ozgartirish": "パスワードを変更する",
        "tilni_ozgartirish": "言語を変更する",
        "akkountdan_chiqish": "サインアウト",
        "web_sahifasi": "webページ",
        "youtube_sahifasi": "youtubeページ",
        "facebook_sahifasi": "facebookページ",
        "instagram_sahifasi": "instagramページ",
        "telegram_sahifasi": "telegramチャンネル",
        "twitter_sahifasi": "twitter(x)ページ"
    },
    "uzb": {
        "xabarlar": "Xabarlar",
        "saqlanganlar": "Saqlanganlar",
        "linklar": "Linklar",
        "sozlamalar": "Sozlamalar",
        "ism": "ism",
        "familiya": "familiya",
        "id_raqami": "id raqami",
        "telefon_raqami": "telefon raqami",
        "raqamni_ozgartirish": "Raqamni o'zgartirish",
        "parolni_ozgartirish": "Parolni o'zgartirish",
        "tilni_ozgartirish": "Tilni o'zgartirish",
        "akkountdan_chiqish": "Akkountdan chiqish",
        "web_sahifasi": "Web sahifasi",
        "youtube_sahifasi": "Youtube sahifasi",
        "facebook_sahifasi": "Facebook sahifasi",
        "instagram_sahifasi": "Instagram sahifasi",
        "telegram_sahifasi": "Telegram sahifasi",
        "twitter_sahifasi": "Twitter(X) sahifasi"
    },
    "eng": {
        "xabarlar": "Messages",
        "saqlanganlar": "Saved",
        "linklar": "Links",
        "sozlamalar": "Settings",
        "ism": "name",
        "familiya": "surname",
        "id_raqami": "id number",
        "telefon_raqami": "phone number",
        "raqamni_ozgartirish": "Change number",
        "parolni_ozgartirish": "Change password",
        "tilni_ozgartirish": "Change language",
        "akkountdan_chiqish": "Sign out",
        "web_sahifasi": "Web page",
        "youtube_sahifasi": "YouTube page",
        "facebook_sahifasi": "Facebook page",
        "instagram_sahifasi": "Instagram page",
        "telegram_sahifasi": "Telegram channel",
        "twitter_sahifasi": "Twitter(X) page"
    }
};
